Document: karaokerg
Title: Debian karaokerg Manual
Author: <insert document author here>
Abstract: This manual describes what karaokerg is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/karaokerg/karaokerg.sgml.gz

Format: postscript
Files: /usr/share/doc/karaokerg/karaokerg.ps.gz

Format: text
Files: /usr/share/doc/karaokerg/karaokerg.text.gz

Format: HTML
Index: /usr/share/doc/karaokerg/html/index.html
Files: /usr/share/doc/karaokerg/html/*.html
